### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by joi0104** [JaeYeopHan/gatsby-starter-bee#276]
## Description

npm install 시, 아래와 같은 에러가 발생합니다. 환경은 mac, node v16.6.0, npm v7.20.3, gatsby-cli v3.10.0입니다.

```
npm ERR! code 1
npm ERR! path /Users/choijinyoung/Desktop/my-blog-starter/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
npm ERR! CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR! info sharp Using cached /Users/choijinyoung/.npm/_libvips/libvips-8.9.1-darwin-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.6.0 | darwin | x64
npm ERR! (node:42479) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/bin/python2
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/choijinyoung/Desktop/my-blog-starter/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/choijinyoung/Desktop/my-blog-starter/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/choijinyoung/Desktop/my-blog-starter/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/choijinyoung/.node-gyp/16.6.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/choijinyoung/.node-gyp/16.6.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/choijinyoung/Desktop/my-blog-starter/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/choijinyoung/.node-gyp/16.6.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/choijinyoung/Desktop/my-blog-starter/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "./gyp-mac-tool", line 611, in <module>
npm ERR!     sys.exit(main(sys.argv[1:]))
npm ERR!   File "./gyp-mac-tool", line 28, in main
npm ERR!     exit_code = executor.Dispatch(args)
npm ERR!   File "./gyp-mac-tool", line 43, in Dispatch
npm ERR!     return getattr(self, method)(*args[1:])
npm ERR!   File "./gyp-mac-tool", line 246, in ExecFilterLibtool
npm ERR!     if not libtool_re.match(line) and not libtool_re5.match(line):
npm ERR! TypeError: cannot use a string pattern on a bytes-like object
npm ERR! make: *** [Release/nothing.a] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/choijinyoung/Desktop/my-blog-starter/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 20.5.0
npm ERR! gyp ERR! command "/Users/choijinyoung/.nvm/versions/node/v16.6.0/bin/node" "/Users/choijinyoung/Desktop/my-blog-starter/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/choijinyoung/Desktop/my-blog-starter/node_modules/sharp
npm ERR! gyp ERR! node -v v16.6.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/choijinyoung/.npm/_logs/2021-08-01T07_42_31_124Z-debug.log
```

**Comment by JaeYeopHan** [comment]
not support node 16.x.x
(i'll add docs)
